apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backtest
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 9999
  selector:
    app: backtest
    tier: backend