kind: Service
apiVersion: v1
metadata:
  name: backend-page
spec:
  type: LoadBalancer
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      nodePort: 32000
  selector:
    app: backend-page