apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
      - name: db
        image: mongo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 27017