kind: Service
apiVersion: v1
metadata:
  name: frontend-page
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: frontend-page