kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-page
  template:
    metadata:
      labels:
        app: frontend-page
    spec:
      containers:
        - name: frontend-page
          image: tonklarepo/frontendpage
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
        
        
        