apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: backtest
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: backtest
        tier: frontend
    spec:
      containers:
      - name: backtest
        image: tonklarepo/fronttest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000