apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    app: redis
    tier: backend